apiVersion: v1
kind: Secret
metadata:
  name: geoapi-db
  namespace: geoapi
type: Opaque
stringData:
  DATABASE_URL: postgresql://geoapi:yGJ8wnOCQhqOb1Lkuak4dOC2IuHDBA0K1oxsSihi3GkG8q3CJa3atnKdWeOfPcmi@sina-db-rw.postgres.svc.cluster.local:5432/geoapi
