apiVersion: v1
kind: Secret
metadata:
  name: ghcr-cred
  namespace: geoapi
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoic2luYWU5OSIsInBhc3N3b3JkIjoiZ2hwX3BhdXdwdVBndWdmVXI1VnI1dTVUSGFqRkJPUlpVWTByY2JMbSIsImF1dGgiOiJjMmx1WVdVNU9UcG5hSEJmY0dGMWQzQjFVR2QxWjJaVmNqVldjalYxTlZSSVlXcEdRazlTV2xWWk1ISmpZa3h0In19fQ==
