#!/usr/bin/env bash

# Strict mode makes missing Terraform state or malformed inventory fail fast.
set -euo pipefail

# Resolve paths relative to this script so it works from any shell location.
ROOT="$(cd "$(dirname "$0")" && pwd)"
INFRA_DIR="${ROOT}/../infra"
INV_DIR="${ROOT}/inventory/mycluster"

# Refuse to run unless Terraform has already created a state file.
if [[ ! -d "${INFRA_DIR}/.terraform" ]] && [[ ! -f "${INFRA_DIR}/terraform.tfstate" ]]; then
  echo "error: no terraform state in ${INFRA_DIR}; run terraform apply first" >&2
  exit 1
fi

# Read the structured VM output and the SSH user from Terraform.
NODES_JSON="$(terraform -chdir="${INFRA_DIR}" output -json nodes)"
SSH_USER="$(terraform -chdir="${INFRA_DIR}" output -raw ssh_user)"

# Python is used here because the inventory is easier to assemble as YAML text.
python3 - "${NODES_JSON}" "${SSH_USER}" "${INV_DIR}" <<'PY'
import json
import sys
from pathlib import Path

# Parse the exact JSON emitted by Terraform.
nodes = json.loads(sys.argv[1])
ssh_user = sys.argv[2]
inv_dir = Path(sys.argv[3])

# These are the only nodes this challenge expects.
required = ("vm1", "vm2", "vm3")
missing = [n for n in required if n not in nodes]
if missing:
    raise SystemExit(f"error: expected vm1/vm2/vm3 in terraform output; missing: {', '.join(missing)}")

# Validate that each node has both the public and private IPs needed by Kubespray.
for name in required:
    node = nodes[name]
    if not node.get("public"):
        raise SystemExit(f"error: {name} has no public IP; add it to infra/terraform.tfvars public_ips")
    if not node.get("private"):
        raise SystemExit(f"error: {name} has no private IP; check terraform output nodes")

# Build one YAML host block per node.
def host_block(name: str) -> str:
    n = nodes[name]
    return (
        f"    {name}:\n"
        f"      ansible_host: {n['public']}\n"
        f"      ip: {n['private']}\n"
        f"      ansible_user: {ssh_user}\n"
    )

# Compose the complete Kubespray inventory as YAML text.
hosts_yaml = (
    "all:\n"
    "  hosts:\n"
    + host_block("vm1")
    + host_block("vm2")
    + host_block("vm3")
    + "  children:\n"
    "    kube_control_plane:\n"
    "      hosts:\n"
    "        vm1: {}\n"
    "    etcd:\n"
    "      hosts:\n"
    "        vm1: {}\n"
    "    kube_node:\n"
    "      hosts:\n"
    "        vm2: {}\n"
    "        vm3: {}\n"
    "    k8s_cluster:\n"
    "      children:\n"
    "        kube_control_plane: {}\n"
    "        kube_node: {}\n"
)

# Kubespray needs the API server cert SANs to include both public and private addresses.
vm1_public = nodes["vm1"]["public"]
vm1_private = nodes["vm1"]["private"]

k8s_cluster_yml = f"""# Generated by generate-inventory.sh — re-run after terraform changes.
kube_network_plugin: calico

# Kubespray v2.28 uses this name (not kube_apiserver_cert_extra_sans).
supplementary_addresses_in_ssl_keys:
  - {vm1_public}
  - {vm1_private}
"""

# Write the inventory files into the Kubespray tree.
inv_dir.mkdir(parents=True, exist_ok=True)
(inv_dir / "hosts.yaml").write_text(hosts_yaml)
(inv_dir / "group_vars" / "k8s_cluster").mkdir(parents=True, exist_ok=True)
(inv_dir / "group_vars" / "k8s_cluster" / "k8s-cluster.yml").write_text(k8s_cluster_yml)

print("Wrote inventory/mycluster/hosts.yaml")
print("Wrote inventory/mycluster/group_vars/k8s_cluster/k8s-cluster.yml")
PY
