apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sina-db
  namespace: postgres
spec:
  instances: 2
  bootstrap:
    initdb:
      database: geoapi
      owner: geoapi
  storage:
    size: 5Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  postgresql:
    parameters:
      shared_buffers: "64MB"
      max_connections: "50"
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
