apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: geoapi
  namespace: argocd
spec:
  description: GitOps project for the GeoAPI workload
  sourceRepos:
    - https://github.com/sinae99/SREv1.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: geoapi
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
